#
# Ubuntu laptop playbook for utils
#

- name: check capslock func
  command: "dconf read /org/gnome/desktop/input-sources/xkb-options"
  register: cps
  changed_when: False

- name: enable keyboard plugin
  command: dconf reset /org/gnome/settings-daemon/plugins/keyboard/active
  when: cps.stdout != "['ctrl:nocaps']"

- name: capslock works as ctrl
  command: dconf write /org/gnome/desktop/input-sources/xkb-options "['ctrl:nocaps']"
  when: cps.stdout != "['ctrl:nocaps']"
  
- name: install Emoji font
  apt: name=ttf-ancient-fonts state=present
  sudo: yes

- name: install ibus-mozc
  sudo: yes
  apt: name={{ item }}
  with_items:
    - ibus-mozc
    - mozc-server
    - mozc-utils-gui

- name: copy mozc conf file
  sudo: yes
  copy: src=./roles/utils/files/mozc.xml dest=/usr/share/ibus/component/mozc.xml
  
- name: copy mozc keymap file
  copy: src=./roles/utils/files/config1.db dest=~/.mozc/config1.db

- name: inport keymap your self
  command : ibus-setup

- name: change the keybind like Emacs
  command: gsettings set org.gnome.desktop.interface gtk-key-theme Emacs

- name: Switch directory language to English
  shell: 'LANG=C xdg-user-dirs-gtk-update'
